package pong;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FeGa
 */
public class Frmpong extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form Frmpong
     */
    
    int pelotaX= 290,pelotaY=200;
    int signo=1;
    int signo2=1;
    
    int paleta1=150;
    int paleta2=150;
    int tope=20;
    int medidaiz=0;
    int medidader=0;
    int jugador1=0;
    int jugador2=0;
    
    public Frmpong() {
        initComponents();
        addKeyListener(this);
    }
    
    public void keyTyped(KeyEvent e) {} //cuando se aplasta la function key
    public void keyReleased(KeyEvent e) {} // cuando suleta la tecla
    public void keyPressed(KeyEvent e) // cuando se presiona la tecla
    {
       System.out.println(e.getKeyCode());
       if (e.getKeyCode()==38)
       {
           paleta2-=20;
       }
       if (e.getKeyCode()==40)
       {
           paleta2+=20;
       }
       if (e.getKeyCode()==65)
       {
           paleta1-=20;
       }
       if (e.getKeyCode()==90)
       {
           paleta1+=20;
       }
    
    }

    
    public void paint(Graphics g) // g es de tipo graphics
    {
        super.paint(g);
        g.drawOval(pelotaX, pelotaY, 20, 20);
        g.drawRect(0, paleta1, tope, 60);
        g.drawRect(580, paleta2, tope, 60);
        repaint();
    }
    
    Timer temporizador = new Timer(10, new ActionListener()
    {
        public void actionPerformed(ActionEvent e)
        {
            pelotaX+=signo*2; // el uno es incremnto de avance
            pelotaY+=signo2*2;
            //if (pelotaX<=0 || pelotaX>=580) 
            //{
              //  signo*=-1;
                                     
            //}
            
            if (pelotaY<= 30 || pelotaY >=380)
            {
                signo2*=-1;
            }
             
            //medidaiz=paleta1+60;
            if (pelotaX==20 && pelotaY>=paleta1-20 && pelotaY<=paleta1+70)

            {
                signo*=-1;
            }
            
            if (pelotaX==560 && pelotaY>=paleta2-20 && pelotaY<=paleta2+70)

            {
                signo*=-1;
            }
            Condicion();
            
            if (paleta1>340)
            {
                paleta1=340;
            }
            if (paleta1<30)
            {
                paleta1=30;
            }
            if (paleta2>340)
            {
                paleta2=340;
            }
            if (paleta2<30)
            {
                paleta2=30;
            }
                                
            
        }
});
    
    public void Condicion()
    {
        if (pelotaX>=600 && pelotaX<=601)
        {
            
            jugador1++;
            lbl1.setText(String.valueOf(jugador1));
            pelotaX=290;
            pelotaY=200; 
            signo*=-1;
            
        }
        if (pelotaX<=0 && pelotaX>=-1)
        {
            jugador2++;
            lbl2.setText(String.valueOf(jugador2));
            pelotaX=290;
            pelotaY=200;
            signo*=-1;
            
                               
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        temporizador.start();
        lbl1.setText(String.valueOf(jugador1));
        lbl2.setText(String.valueOf(jugador2));
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmpong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
