package javaapplication87;

import java.applet.AudioClip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FeGa
 */
public class FrmPptls extends javax.swing.JFrame {

    int aleatorio;
    
    int marcadorcompu=0;
    int marcadorjugador=0;
    int suma1;
    int suma2;
    int resp1;
    int resp2;
    
    public FrmPptls() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void Bloquear()
    {
        btnPapel.setEnabled(false);
        btnPiedra.setEnabled(false);
        btntijera.setEnabled(false);
        btnlagarto.setEnabled(false);
        btnspock.setEnabled(false);
    }
    
    public void imagenes()
    {
        btnPiedra.setIcon(new ImageIcon(this.getClass().getResource("piedra.png")));
        btnPapel.setIcon(new ImageIcon(this.getClass().getResource("papel.png")));
        btntijera.setIcon(new ImageIcon(this.getClass().getResource("tijera.png")));
        btnlagarto.setIcon(new ImageIcon(this.getClass().getResource("lagarto.png")));
        btnspock.setIcon(new ImageIcon(this.getClass().getResource("spock.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPiedra = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btntijera = new javax.swing.JButton();
        btnspock = new javax.swing.JButton();
        btnlagarto = new javax.swing.JButton();
        btnjugar = new javax.swing.JButton();
        txtcompu = new javax.swing.JTextField();
        txtjugador = new javax.swing.JTextField();
        lblmarcador = new javax.swing.JLabel();
        lblcompu = new javax.swing.JLabel();
        lbljugador = new javax.swing.JLabel();
        btnreglas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraActionPerformed(evt);
            }
        });

        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btntijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntijeraActionPerformed(evt);
            }
        });

        btnspock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspockActionPerformed(evt);
            }
        });

        btnlagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlagartoActionPerformed(evt);
            }
        });

        btnjugar.setText("Jugar");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        txtcompu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcompu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompuActionPerformed(evt);
            }
        });

        txtjugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblmarcador.setText("Marcador");

        lblcompu.setText("Computadora");

        lbljugador.setText("Jugador");

        btnreglas.setText("Reglas");
        btnreglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreglasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblmarcador)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnreglas)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnjugar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnspock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntijera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 186, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblcompu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcompu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbljugador, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnspock, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntijera, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblmarcador)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcompu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcompu)
                            .addComponent(lbljugador))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnreglas)
                .addGap(41, 41, 41)
                .addComponent(btnjugar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiedraActionPerformed
        Bloquear();
        
        if (aleatorio == 1)
        {
            JOptionPane.showMessageDialog(null, "empate");
        }
        
        else if ((aleatorio == 2) || (aleatorio == 5))
        {
            JOptionPane.showMessageDialog(null, "perdiste");
            suma1=Integer.valueOf(txtcompu.getText());
            resp1=suma1+1;
            txtcompu.setText(String.valueOf(resp1));
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "ganaste");
            suma2=Integer.valueOf(txtjugador.getText());
            resp2=suma2+1;
            txtjugador.setText(String.valueOf(resp2));
        }
        
    }//GEN-LAST:event_btnPiedraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //aleatorio = (int)(Math.random()*5+1);
        //System.out.print(aleatorio);
        txtcompu.setText(String.valueOf(marcadorcompu));
        txtjugador.setText(String.valueOf(marcadorjugador));
        txtcompu.setEditable(false);
        txtjugador.setEditable(false);
        Bloquear();
        JOptionPane.showMessageDialog(null, "Bienvenido al juego de piedra, papel, tijera, lagarto, spock \nPara empezar presiona el botón 'Jugar' \nSi quieres seguir jugando vuelve a presionar el mismo botón \nSi quieres escuchar las reglas has clikc en el botón reglas ");
                       
    }//GEN-LAST:event_formWindowOpened

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        Bloquear();
        if (aleatorio == 2)
        {
            JOptionPane.showMessageDialog(null, "empate");
        }
        
        else if ((aleatorio == 3) || (aleatorio == 4))
        {
            JOptionPane.showMessageDialog(null, "perdiste");
            suma1=Integer.valueOf(txtcompu.getText());
            resp1=suma1+1;
            txtcompu.setText(String.valueOf(resp1));
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "ganaste");
            suma2=Integer.valueOf(txtjugador.getText());
            resp2=suma2+1;
            txtjugador.setText(String.valueOf(resp2));
        }
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btntijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntijeraActionPerformed
        Bloquear();
        if (aleatorio == 3)
        {
            JOptionPane.showMessageDialog(null, "empate");
        }
        
        else if ((aleatorio == 1) || (aleatorio == 5))
        {
            JOptionPane.showMessageDialog(null, "perdiste");
            suma1=Integer.valueOf(txtcompu.getText());
            resp1=suma1+1;
            txtcompu.setText(String.valueOf(resp1));
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "ganaste");
            suma2=Integer.valueOf(txtjugador.getText());
            resp2=suma2+1;
            txtjugador.setText(String.valueOf(resp2));
        }
    }//GEN-LAST:event_btntijeraActionPerformed

    private void btnlagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlagartoActionPerformed
        Bloquear();
        if (aleatorio == 4)
        {
            JOptionPane.showMessageDialog(null, "empate");
        }
        
        else if ((aleatorio == 2) || (aleatorio == 5))
        {
            JOptionPane.showMessageDialog(null, "ganaste");
            suma2=Integer.valueOf(txtjugador.getText());
            resp2=suma2+1;
            txtjugador.setText(String.valueOf(resp2));
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "perdiste");
            suma1=Integer.valueOf(txtcompu.getText());
            resp1=suma1+1;
            txtcompu.setText(String.valueOf(resp1));
        }
    }//GEN-LAST:event_btnlagartoActionPerformed

    private void btnspockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspockActionPerformed
        Bloquear();
        if (aleatorio == 5)
        {
            JOptionPane.showMessageDialog(null, "empate");
        }
        
        else if ((aleatorio == 1) || (aleatorio == 3))
        {
            JOptionPane.showMessageDialog(null, "ganaste");
            suma2=Integer.valueOf(txtjugador.getText());
            resp2=suma2+1;
            txtjugador.setText(String.valueOf(resp2));
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "perdiste");
            suma1=Integer.valueOf(txtcompu.getText());
            resp1=suma1+1;
            txtcompu.setText(String.valueOf(resp1));
        }
    }//GEN-LAST:event_btnspockActionPerformed

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        aleatorio = (int)(Math.random()*5+1);
        System.out.print(aleatorio);
        AudioClip sonido2;
        sonido2= java.applet.Applet.newAudioClip(getClass().getResource("jugar.wav"));
        sonido2.play();
        
        imagenes();
        
        
        btnPapel.setEnabled(true);
        btnPiedra.setEnabled(true);
        btntijera.setEnabled(true);
        btnlagarto.setEnabled(true);
        btnspock.setEnabled(true);
    }//GEN-LAST:event_btnjugarActionPerformed

    private void txtcompuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompuActionPerformed

    private void btnreglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreglasActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("reglaspptls.wav"));
        sonido.play();
    }//GEN-LAST:event_btnreglasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPptls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPptls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPptls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPptls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPptls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPiedra;
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton btnlagarto;
    private javax.swing.JButton btnreglas;
    private javax.swing.JButton btnspock;
    private javax.swing.JButton btntijera;
    private javax.swing.JLabel lblcompu;
    private javax.swing.JLabel lbljugador;
    private javax.swing.JLabel lblmarcador;
    private javax.swing.JTextField txtcompu;
    private javax.swing.JTextField txtjugador;
    // End of variables declaration//GEN-END:variables
}
